// Real templates from Notion "Agents Database" (22 of ~150 visible).
// Schema mirrors the Notion DB: oneliner, output, platform, tools, trigger, wedge.
// Investor Update Brief is fully populated from the property page. The other 21
// have partial details from the table view + reasonable extrapolations; swap with
// the canonical values when you export the full Notion CSV.
export const TEMPLATES = [
  { id: "due-diligence-memory", name: "Due Diligence Memory", category: "Fundraising", icon: "📒",
    oneliner: "Recalls every DD question asked across rounds; flags duplicate asks before you re-answer them.",
    output: "Slack DM to <Reviewer Name> with answer + provenance. On `ship it`, saves to the DD Memory Notion DB.",
    platform: ["Slack", "Email"], tools: ["Memory Store", "Slack", "Gmail", "Notion"],
    trigger: "Webhook on inbound DD email", wedge: "Cross-session recall",
    keywords: ["due diligence", "dd", "investor", "fundraising", "data room"] },

  { id: "investor-update-brief", name: "Investor Update Brief", category: "Fundraising", icon: "📈",
    oneliner: "Pre-investor-update, briefs founder on metrics changes since last update.",
    output: "Slack DM to <Reviewer Name> at <Channel Name> with founder-facing brief + draft outgoing update. On `ship it`, saves brief to Notion Investor Updates DB and stages a Gmail draft (never auto-sent).",
    platform: ["Slack", "Notion", "Email"], tools: ["Memory Store", "Slack", "Notion", "Gmail"],
    trigger: "Cron monthly at 06:00 on the 1st (`0 6 1 * *`). Manual: `/investor-brief` in <Channel Name>.",
    wedge: "Cross-session recall",
    keywords: ["investor", "update", "brief", "fundraising", "monthly", "cap"] },

  { id: "exit-interview-memory", name: "Exit Interview Memory", category: "HR", icon: "🚪",
    oneliner: "Captures exit reasons; surfaces patterns across departures so you spot systemic issues.",
    output: "Slack DM to <Reviewer Name> after each exit; weekly pattern digest.",
    platform: ["Slack", "Notion"], tools: ["Memory Store", "Slack", "Notion", "Granola"],
    trigger: "Event on Granola tag 'exit-interview'", wedge: "Pattern surfacing",
    keywords: ["exit interview", "departure", "attrition", "hr", "feedback"] },

  { id: "long-running-project", name: "Long-running Project Agent", category: "Operations", icon: "📊",
    oneliner: "Persists state, plans, and learnings across a multi-quarter project so context never resets.",
    output: "Slack DM to <Reviewer Name> with weekly state summary; updates Linear tickets.",
    platform: ["Slack", "Notion"], tools: ["Memory Store", "Slack", "Linear", "Notion"],
    trigger: "Cron weekly Monday 08:00", wedge: "Cross-session recall",
    keywords: ["project", "long-running", "ops", "plan", "state"] },

  { id: "cross-agent-resolver", name: "Cross-Agent Reference Resolver", category: "Infrastructure", icon: "🔗",
    oneliner: "Resolves 'the X we discussed' across agents — shared memory so agents stop talking past each other.",
    output: "Synchronous return to the calling agent.",
    platform: ["Slack"], tools: ["Memory Store", "Slack"],
    trigger: "Synchronous call from other agents", wedge: "Shared agent memory",
    keywords: ["reference", "resolver", "shared memory", "cross-agent", "infrastructure"] },

  { id: "perf-review-memory", name: "Performance Review Memory", category: "HR", icon: "📊",
    oneliner: "Recalls each report's commitments, wins, and gaps so review cycles aren't a recency-bias contest.",
    output: "Private Slack DM to <Reviewer> with each report's full-cycle dossier.",
    platform: ["Slack", "Notion"], tools: ["Memory Store", "Slack", "Notion", "Gmail"],
    trigger: "Cron quarterly + manual `/perf-review @user`", wedge: "Recency-bias correction",
    keywords: ["performance review", "1:1", "manager", "hr", "feedback"] },

  { id: "engagement-survey-memory", name: "Engagement Survey Memory", category: "HR", icon: "📝",
    oneliner: "Recalls survey signals over time; flags drift before the next pulse turns red.",
    output: "Slack DM to <Reviewer Name> with drift flags after each pulse.",
    platform: ["Slack", "Notion"], tools: ["Memory Store", "Slack", "Notion"],
    trigger: "Webhook on new survey response", wedge: "Longitudinal trend recall",
    keywords: ["engagement", "survey", "pulse", "hr", "morale"] },

  { id: "inbox-triage-memory", name: "Inbox Triage Memory", category: "Productivity", icon: "✉️",
    oneliner: "Recalls past triage decisions; learns who matters and what you actually open vs archive.",
    output: "Slack DM to <Reviewer Name> with overnight triage + reasons.",
    platform: ["Slack", "Email"], tools: ["Memory Store", "Slack", "Gmail"],
    trigger: "Cron daily 07:00", wedge: "Learned triage memory",
    keywords: ["inbox", "email", "triage", "gmail", "productivity"] },

  { id: "hire-pipeline-brief", name: "Hire Pipeline Brief", category: "HR", icon: "🧲",
    oneliner: "Daily brief on top-of-funnel candidates: who's hot, who's stalled, who needs a nudge.",
    output: "Slack DM to <Reviewer Name> with daily pipeline brief; LinkedIn nudges drafted.",
    platform: ["Slack", "Notion", "Email"], tools: ["Memory Store", "Slack", "Notion", "Gmail", "LinkedIn"],
    trigger: "Cron daily 09:00", wedge: "Pipeline state recall",
    keywords: ["hiring", "recruiting", "pipeline", "candidates", "hr"] },

  { id: "trademark-memory", name: "Trademark Memory", category: "Legal", icon: "™️",
    oneliner: "Recalls past trademark searches and filings; warns before you re-litigate a settled question.",
    output: "Slack DM to <Reviewer Name> with prior-search results.",
    platform: ["Slack", "Notion"], tools: ["Memory Store", "Slack", "WebSearch", "Notion"],
    trigger: "Manual: `/tm <name>`", wedge: "Cross-session recall",
    keywords: ["trademark", "ip", "legal", "filing"] },

  { id: "privacy-request-memory", name: "Privacy Request Memory", category: "Compliance", icon: "🔒",
    oneliner: "Recalls every privacy request (DSAR, deletion, etc.) with status, deadline, and who handled it.",
    output: "Slack DM to <Reviewer Name> + Notion log entry per request.",
    platform: ["Slack", "Email", "Notion"], tools: ["Memory Store", "Slack", "Gmail", "Notion"],
    trigger: "Webhook on inbound privacy email", wedge: "Compliance audit trail",
    keywords: ["privacy", "dsar", "gdpr", "compliance", "request"] },

  { id: "reference-check-memory", name: "Reference Check Memory", category: "HR", icon: "📞",
    oneliner: "Recalls what each reference said for every candidate; surfaces flags before you make the offer.",
    output: "Slack DM to <Reviewer Name> with reference dossier per candidate.",
    platform: ["Slack", "Notion"], tools: ["Memory Store", "Slack", "Notion", "Granola"],
    trigger: "Event on Granola tag 'reference-check'", wedge: "Cross-call pattern surfacing",
    keywords: ["reference check", "hiring", "candidate", "hr"] },

  { id: "personal-daily-update", name: "Personal Daily Update Agent", category: "Personal", icon: "🌅",
    oneliner: "DMs a person their daily summary: what shipped, what's overdue, what's on their plate today.",
    output: "Per-user Slack DM (one message per teammate at start of day).",
    platform: ["Slack"], tools: ["Memory Store", "Slack", "Linear", "GitHub"],
    trigger: "Cron daily 08:00 per timezone", wedge: "Per-individual context",
    keywords: ["daily", "summary", "personal", "morning", "standup"] },

  { id: "reading-list-memory", name: "Reading List Memory", category: "Personal", icon: "📚",
    oneliner: "Recalls what you've read and what you saved; nudges you back to the article you bookmarked 3 weeks ago.",
    output: "Event mode: one-line confirmation; weekly resurfacing digest.",
    platform: ["Slack"], tools: ["Memory Store", "Slack", "WebSearch"],
    trigger: "Event on bookmark/save", wedge: "Spaced-recall resurfacing",
    keywords: ["reading", "articles", "bookmarks", "personal", "library"] },

  { id: "dpa-negotiation-memory", name: "DPA Negotiation Memory", category: "Legal", icon: "📄",
    oneliner: "Recalls each customer's data-processing terms and your acceptable redlines so legal stops repeating itself.",
    output: "Slack DM to <Reviewer Name> with redline diff vs. prior precedent.",
    platform: ["Slack", "Email", "Notion"], tools: ["Memory Store", "Slack", "Gmail", "Notion"],
    trigger: "Webhook on inbound DPA email", wedge: "Redline precedent recall",
    keywords: ["dpa", "legal", "data processing", "contract", "negotiation"] },

  { id: "cap-table-history", name: "Cap Table History Memory", category: "Fundraising", icon: "📊",
    oneliner: "Recalls each shareholder's history: when they came in, at what price, with what rights.",
    output: "Slack DM to <Reviewer Name> with shareholder dossier on request.",
    platform: ["Slack", "Notion"], tools: ["Memory Store", "Slack", "Notion", "Gmail"],
    trigger: "Event on cap-table edits + manual `/captable`", wedge: "Decision-history recall",
    keywords: ["cap table", "shareholder", "equity", "fundraising"] },

  { id: "travel-memory", name: "Travel Memory Agent", category: "Personal", icon: "🧳",
    oneliner: "Recalls each trip's bookings, preferences, and what went wrong; plans the next one accordingly.",
    output: "Slack DM with trip plan + booking links.",
    platform: ["Slack"], tools: ["Memory Store", "Slack", "Calendar", "Gmail", "WebSearch"],
    trigger: "Event on calendar 'trip' event + manual", wedge: "Personal-preference recall",
    keywords: ["travel", "trip", "personal", "flight", "hotel"] },

  { id: "risk-register-memory", name: "Risk Register Memory", category: "Compliance", icon: "⚠️",
    oneliner: "Captures risks raised; surfaces patterns and warns when an old risk re-emerges in a new form.",
    output: "Slack DM to <Reviewer Name> with risk diff + pattern warning.",
    platform: ["Slack", "Notion"], tools: ["Memory Store", "Slack", "Notion", "Granola"],
    trigger: "Event on Granola tag 'risk'", wedge: "Pattern re-emergence",
    keywords: ["risk", "register", "compliance", "governance"] },

  { id: "compliance-audit-trail", name: "Compliance / Audit Trail Agent", category: "Compliance", icon: "✅",
    oneliner: "Records who decided what and when; reconstructs the audit trail for any decision on demand.",
    output: "Slack DM to <Reviewer Name> with decision chain on request.",
    platform: ["Slack", "Notion"], tools: ["Memory Store", "Slack", "Notion", "Granola", "GitHub"],
    trigger: "Event on Slack/GitHub decision markers", wedge: "Decision-chain reconstruction",
    keywords: ["audit", "compliance", "decision log", "soc2", "governance"] },

  { id: "skill-inventory-memory", name: "Skill Inventory Memory", category: "HR", icon: "🧠",
    oneliner: "Recalls who knows what across the team; surfaces gaps before a hire is the only answer.",
    output: "Add mode: Slack DM to <Reviewer Name>; query mode: synchronous answer.",
    platform: ["Slack", "Notion"], tools: ["Memory Store", "Slack", "Notion", "LinkedIn", "Granola"],
    trigger: "Event on hiring/standup signals", wedge: "Skill-gap surfacing",
    keywords: ["skills", "inventory", "team", "hr", "expertise"] },

  { id: "personal-preference-agent", name: "Personal Preference Agent", category: "Personal", icon: "⭐",
    oneliner: "Remembers an individual's tools, formats, and quirks so any agent talking to them speaks their language.",
    output: "Add + sweep modes: Slack DM with confirmed preferences.",
    platform: ["Slack"], tools: ["Memory Store", "Slack", "Calendar", "Gmail"],
    trigger: "Event on user interactions; weekly sweep", wedge: "Per-individual context",
    keywords: ["preferences", "personal", "individual", "style"] },

  { id: "onboarding-buddy", name: "Onboarding Buddy", category: "HR", icon: "👋",
    oneliner: "Answers new-hire questions from the org's actual history — high-confidence direct Slack, low-confidence routes to a human.",
    output: "High-confidence: direct Slack reply. Low-confidence: routes to <Reviewer Name>.",
    platform: ["Slack", "Notion"], tools: ["Memory Store", "Slack", "Notion", "Granola"],
    trigger: "Event on new-hire DM + Slack mention", wedge: "Org-history recall",
    keywords: ["onboarding", "new hire", "hr", "buddy"] },
];
