import { assemblePrompt } from "../lib/prompts.js";
import { generateProfileSummary } from "../lib/profile.js";

/**
 * Generate a complete SKILL.md string from quiz dimension scores.
 *
 * @param {{ density: number, exploration: string, confidence: number, tone: number, engagement: number, intent: string, candor: number }} profile
 * @returns {string} Complete SKILL.md content
 */
export function generateSkill(profile) {
  const summary = generateProfileSummary(profile);
  const prompt = assemblePrompt(profile);

  const summaryText = summary.headline + "\n\n" +
    summary.details.map(d => "- " + d).join("\n");

  return `---
name: learning-style
description: >
  This skill contains the user's personal learning and communication
  preferences, discovered through memories.new/fig. Apply these preferences
  in ALL conversations — every response should reflect the style described
  below. Adjust tone, information density, explanation style, and engagement
  level to match this profile. This is not optional context; it is the
  primary instruction for how to communicate with this user.
---

# Learning Style Preferences

These preferences were discovered through an interactive assessment at
memories.new. They describe how this person best receives and processes
information.

## Profile Summary

${summaryText}

## Instructions for AI Assistants

${prompt}

## About This File

This is a skill file generated by memories.new/fig. It works with any
AI assistant that accepts custom instructions or system prompts:

- **Claude:** Drop into any Project, or paste the instructions above
  into a conversation
- **ChatGPT:** Paste the instructions into Custom Instructions or at
  the start of a conversation
- **Other assistants:** Use the Instructions section as a system prompt

Regenerate anytime at memories.new/fig
`;
}
